baseURL = "https://boh5.com/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"

title = "黄波的博客"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "FixIt"

# 作者配置
[author]
name = "黄波"
email = ""
link = "https://boh5.com"

# 网站地图配置
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks 配置 (https://gohugo.io/content-management/urls#permalinks)
[permalinks]
# posts = ":year/:month/:filename"
"/" = ":sections/:filename"

# 隐私信息配置 (https://gohugo.io/about/hugo-and-gdpr/)
[privacy]
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

#
[mediaTypes]
# 用于输出 Markdown 格式文档的设置
[mediaTypes."text/markdown"]
suffixes = ["md"]
# 用于输出 txt 格式文档的设置
[mediaTypes."text/plain"]
suffixes = ["txt"]

#
[outputFormats]
# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
mediaType = "text/markdown"
isPlainText = true
isHTML = false
#  用于输出 baidu_urls.txt 文件的设置
[outputFormats.BaiduUrls]
baseName = "baidu_urls"
mediaType = "text/plain"
isPlainText = true
isHTML = false

#  用于 Hugo 输出文档的设置
[outputs]
home = ["HTML", "RSS", "JSON", "BaiduUrls"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]
