#  FixIt 主题版本
version = "0.2.X" # 例如："0.2.X", "0.2.15", "v0.2.15" 等
# 网站描述
description = "Python、后端、笔记和技术分享"
# 网站关键词
keywords = ["Blog", "HuangBo", "黄波", "后端", "开发", "学习笔记"]
# 网站默认主题样式 ("light", "dark", "auto")
defaultTheme = "auto"
# 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
gitRepo = ""
#  哪种哈希函数用来 SRI, 为空时表示不使用 SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
#  日期格式
dateFormat = "2006-01-02"
# 网站图片，用于 Open Graph 和 Twitter Cards
images = ["/logo.png"]
#  开启 PWA 支持
enablePWA = true
#  是否自动显示外链图标
externalIcon = false
#  默认情况下，FixIt 只会在主页的 HTML 头中注入主题元标记。
# 您可以将其关闭，但如果您不这样做，我们将不胜感激，因为这是观察 FixIt 受欢迎程度上升的好方法。
disableThemeInject = false

#  应用图标配置
[app]
# 当添加到 iOS 主屏幕或者 Android 启动器时的标题，覆盖默认标题
title = "黄波的博客"
# 是否隐藏网站图标资源链接
noFavicon = false
# 更现代的 SVG 网站图标，可替代旧的 .png 和 .ico 文件
svgFavicon = ""
# Safari 图标颜色
iconColor = "#5bbad5"
# Windows v8-10 磁贴颜色
tileColor = "#da532c"
#  Android 浏览器主题色
[app.themeColor]
light = "#ffffff"
dark = "#252627"

#  搜索配置
[search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
#  最大结果数目
maxResultLength = 10
#  结果内容片段长度
snippetLength = 50
#  搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
#  是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false
[search.algolia]
index = ""
appID = ""
searchKey = ""

# 页面头部导航栏配置
[header]
#  桌面端导航栏模式 ("sticky", "normal", "auto")
desktopMode = "sticky"
#  移动端导航栏模式 ("sticky", "normal", "auto")
mobileMode = "auto"
#  页面头部导航栏标题配置
[header.title]
# LOGO 的 URL
logo = "/apple-touch-icon.png"
# 标题名称
name = "黄波的博客"
# 你可以在名称（允许 HTML 格式）之前添加其他信息，例如图标
pre = ""
# 你可以在名称（允许 HTML 格式）之后添加其他信息，例如图标
post = ""
#  是否为标题显示打字机动画
typeit = false
#  页面头部导航栏副标题配置
[header.subtitle]
# 副标题名称
name = "开发、学习、生活、技术分享"
# 是否为副标题显示打字机动画
typeit = false

# 页面底部信息配置
[footer]
enable = true
#  自定义内容（支持 HTML 格式）
custom = ''
#  是否显示 Hugo 和主题信息
hugo = true
#  是否显示版权信息
copyright = true
#  是否显示作者
author = true
# 网站创立年份
since = 2022
#  网站创立时间
siteTime = '' # 例：'2019-02-03T19:30:34+08:00'
#  是否显示网站内容总字数
wordCount = true
#  公网安备信息，仅在中国使用（支持 HTML 格式）
gov = ""
#  ICP 备案信息，仅在中国使用（支持 HTML 格式）
icp = ""
# 许可协议信息（支持 HTML 格式）
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section（所有文章）页面配置
[section]
# section 页面每页显示文章数量
paginate = 20
# 日期格式（月和日）
dateFormat = "01-02"
# RSS 文章数目
rss = 10
#  最近更新文章设置
[section.recentlyUpdated]
enable = false
rss = false
days = 30
maxCount = 10

#  List（目录或标签）页面配置
[list]
# list 页面每页显示文章数量
paginate = 20
# 日期格式（月和日）
dateFormat = "01-02"
# RSS 文章数目
rss = 10

# 主页配置
[home]
#  RSS 文章数目
rss = 10
# 主页个人信息
[home.profile]
enable = true
#  选择使用 Gravatar 源站或其他镜像站，若留空则为默认的 "www.gravatar.com"
#   参数 `home.profile.gravatarSite` 自 v0.2.14 起已弃用，请改用 `gravatar.host`
# gravatarSite = ""
# Gravatar 邮箱，用于优先在主页显示的头像
gravatarEmail = "bohuang1994@gmail.com"
# 主页显示头像的 URL
avatarURL = ""
#  主页显示的网站标题（支持 HTML 格式）
title = "黄波的博客"
# 主页显示的网站副标题
subtitle = "山无陵，江水为竭，冬雷震震，夏雨雪，天地合，乃敢与君绝！"
# 是否为副标题显示打字机动画
typeit = true
# 是否显示社交账号
social = true
#  免责声明（支持 HTML 格式）
disclaimer = ""
# 主页文章列表
[home.posts]
enable = true
# 主页每页显示文章数量
paginate = 6

# 作者的社交信息设置
[social]
GitHub = "diless"
Linkedin = ""
Twitter = ""
Instagram = ""
Facebook = ""
Telegram = ""
Medium = ""
Gitlab = ""
Youtubelegacy = ""
Youtubecustom = ""
Youtubechannel = ""
Tumblr = ""
Quora = ""
Keybase = ""
Pinterest = ""
Reddit = ""
Codepen = ""
FreeCodeCamp = ""
Bitbucket = ""
Stackoverflow = "4896749"
Weibo = ""
Odnoklassniki = ""
VK = ""
Flickr = ""
Xing = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Bandcamp = ""
Paypal = ""
Fivehundredpx = ""
Mix = ""
Goodreads = ""
Lastfm = ""
Foursquare = ""
Hackernews = ""
Kickstarter = ""
Patreon = ""
Steam = ""
Twitch = ""
Strava = ""
Skype = ""
Whatsapp = ""
Zhihu = ""
Douban = ""
Angellist = ""
Slidershare = ""
Jsfiddle = ""
Deviantart = ""
Behance = ""
Dribbble = ""
Wordpress = ""
Vine = ""
Googlescholar = ""
Researchgate = ""
Mastodon = ""
Thingiverse = ""
Devto = ""
Gitea = ""
XMPP = ""
Matrix = ""
Bilibili = ""
# ORCID, ... , CSDN
ORCID = ""
Liberapay = ""
Ko-Fi = ""
BuyMeaCoffee = ""
Linktree = ""
QQ = ""
QQGroup = "" # https://qun.qq.com/join.html
Diaspora = ""
CSDN = ""
Email = ""
RSS = true #

#  文章页面配置
[page]
#  是否在主页隐藏一篇文章
hiddenFromHomePage = false
#  是否在搜索结果中隐藏一篇文章
hiddenFromSearch = false
#  是否使用 twemoji
twemoji = false
# 是否使用 lightgallery
lightgallery = false
#  是否使用 ruby 扩展语法
ruby = true
#  是否使用 fraction 扩展语法
fraction = true
#  是否使用 fontawesome 扩展语法
fontawesome = true
# 许可协议信息（支持 HTML 格式）
license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
# 是否在文章页面显示原始 Markdown 文档链接
linkToMarkdown = true
#  是否在 RSS 中显示全文内容
rssFullText = false
#  页面样式 ("narrow", "normal", "wide", ...)
pageStyle = "normal"
#  强制使用 Gravatar 作为作者头像
gravatarForce = true
#  转载配置
[page.repost]
enable = false
url = ""
#  目录配置
[page.toc]
# 是否使用目录
enable = true
#  是否保持使用文章前面的静态目录
keepStatic = false
# 是否使侧边目录自动折叠展开
auto = true
#  目录位置 ("left", "right")
position = "right"
#  在文章开头显示提示信息，提醒读者文章内容可能过时
[page.expirationReminder]
enable = true
# 如果文章最后更新于这天数之前，显示提醒
reminder = 90
# 如果文章最后更新于这天数之前，显示警告
warning = 180
# 如果文章到期是否关闭评论
closeComment = false
#  代码配置
[page.code]
# 是否显示代码块的复制按钮
copy = true
#  是否显示代码块的编辑按钮
edit = true
# 默认展开显示的代码行数
maxShownLines = 10
#  文章编辑
[page.edit]
enable = false
#  编辑的基础链接
# url = "/edit/branch-name/subdirectory-name" # 相对于 `gitRepo`
# url = "https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name" # 完整链接
url = ""
#  KaTeX 数学公式 (https://katex.org)
[page.math]
enable = true
# 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# 默认行内定界符是 $ ... $ 和 \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX 插件 copy_tex
copyTex = true
# KaTeX 插件 mhchem
mhchem = true
#  Mapbox GL JS 配置 (https://docs.mapbox.com/mapbox-gl-js)
[page.mapbox]
# Mapbox GL JS 的 access token
accessToken = ""
# 浅色主题的地图样式
lightStyle = "mapbox://styles/mapbox/light-v9"
# 深色主题的地图样式
darkStyle = "mapbox://styles/mapbox/dark-v9"
# 是否添加 NavigationControl
navigation = true
# 是否添加 GeolocateControl
geolocate = true
# 是否添加 ScaleControl
scale = true
# 是否添加 FullscreenControl
fullscreen = true
#  文章页面的分享信息设置
[page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = false
Whatsapp = true
Pinterest = false
Tumblr = false
HackerNews = false
Reddit = false
VK = false
Buffer = false
Xing = false
Line = true
Instapaper = false
Pocket = false
Digg = false
Stumbleupon = false
Flipboard = false
Weibo = true
Renren = false
Myspace = true
Blogger = true
Baidu = false
Odnoklassniki = false
Evernote = true
Skype = false
Trello = false
Mix = false
#  评论系统设置
[page.comment]
enable = true
#  Artalk 评论系统设置 (https://artalk.js.org/)
[page.comment.artalk]
enable = false
server = "https://yourdomain/api/"
site = "默认站点"
placeholder = ""
noComment = ""
sendBtn = ""
editorTravel = true
flatMode = 'auto'
maxNesting = 3
# 当 `page.lightgallery` 启用时生效
lightgallery = false
locale = "" #
#  Disqus 评论系统设置 (https://disqus.com)
[page.comment.disqus]
enable = false
# Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
shortname = ""
#  Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
[page.comment.gitalk]
enable = false
owner = ""
repo = ""
clientId = ""
clientSecret = ""
# Valine 评论系统设置 (https://github.com/xCss/Valine)
[page.comment.valine]
enable = false
appId = ""
appKey = ""
placeholder = ""
avatar = "mp"
meta= ""
pageSize = 10
lang = ""
visitor = true
recordIP = true
highlight = true
enableQQ = false
serverURLs = ""
#  emoji 数据文件名称，默认是 "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# 位于 "themes/FixIt/assets/data/emoji/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件：
# "assets/data/emoji/"
emoji = ""
commentCount = true #
#  Waline 评论系统设置 (https://waline.js.org)
[page.comment.waline]
enable = false
serverURL = ""
pageview = false #
emoji = ['//unpkg.com/@waline/emojis@1.0.1/weibo']
meta = ['nick', 'mail', 'link']
requiredMeta = []
login = 'enable'
wordLimit = 0
pageSize = 10
imageUploader = false #
highlighter = false #
comment = false #
# visitor = false #  更名为 pageview
# uploadImage = false #  更名为 imageUploader
# highlight = true #  更名为 highlighter
# mathTagSupport = false
# commentCount = false  更名为 comment
# Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
[page.comment.facebook]
enable = false
width = "100%"
numPosts = 10
appId = ""
languageCode = "zh_CN"
#  Telegram Comments 评论系统设置 (https://comments.app)
[page.comment.telegram]
enable = false
siteID = ""
limit = 5
height = ""
color = ""
colorful = true
dislikes = false
outlined = false
#  Commento 评论系统设置 (https://commento.io)
[page.comment.commento]
enable = false
#  Utterances 评论系统设置 (https://utteranc.es)
[page.comment.utterances]
enable = false
# owner/repo
repo = ""
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
darkTheme = "github-dark"
#  Twikoo 评论系统设置 (https://twikoo.js.org/)
[page.comment.twikoo]
enable = false
envId = ""
region = ""
path = ""
visitor = true
commentCount = true
# 当 `page.lightgallery` 启用时生效
lightgallery = false
#  Giscus 评论系统设置
[page.comment.giscus]
enable = true
repo = "dilless/dilless.github.io"
repoId = "R_kgDOHr9Jag"
category = "Announcements"
categoryId = "DIC_kwDOHr9Jas4CQ396"
mapping = "title"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom" # top, bottom
lightTheme = "light"
darkTheme = "dark"
lazyLoad = true
#  第三方库配置
[page.library]
[page.library.css]
# someCSS = "some.css"
# 位于 "assets/"
# 或者
# someCSS = "https://cdn.example.com/some.css"
[page.library.js]
# someJavascript = "some.js"
# 位于 "assets/"
# 或者
# someJavascript = "https://cdn.example.com/some.js"
#  页面 SEO 配置
[page.seo]
# 图片 URL
images = []
# 出版者信息
[page.seo.publisher]
name = ""
logoUrl = ""

#  TypeIt 配置
[typeit]
# 每一步的打字速度（单位是毫秒）
speed = 100
# 光标的闪烁速度（单位是毫秒）
cursorSpeed = 1000
# 光标的字符（支持 HTML 格式）
cursorChar = "|"
# 打字结束之后光标的持续时间（单位是毫秒，"-1" 代表无限大）
duration = -1

#  Mermaid 配置
[mermaid]
# 取值详见 https://mermaid-js.github.io/mermaid/#/Setup?id=theme
themes = ['neutral', 'dark']

#  盘古之白配置
[pangu]
# 适用于中文写作用户
enable = false

#  水印配置
# 详细参数见 https://github.com/Lruihao/watermark#readme
[watermark]
enable = false
# 水印内容（允许 HTML 格式）
content = ''
# 水印透明度
opacity = 0.1
# 水印父节点
appendTo = '.wrapper>main'
# 单水印宽度 单位：px
width = 150
# 单水印高度 单位：px
height = 20
# 水印行间距 单位：px
rowSpacing = 60
# 水印列间距 单位：px
colSpacing = 30
# 水印旋转角度 单位：deg
rotate = 15
# 水印字体大小，单位：rem
fontSize = 0.85
#  水印字体
fontFamily = 'inherit'

#  不蒜子统计
[ibruce]
enable = true
# 在文章中开启
enablePost = false
#   网站创立时间
# 参数 `ibruce.siteTime` 自 v0.2.14 起已弃用，请改用 `footer.siteTime`
# siteTime = '' # 例：'2019-02-03T19:30:34+08:00'
# 网站验证代码，用于 Google/Bing/Yandex/Pinterest/Baidu/360/Sogou
[verification]
google = "3_Zf27e0mNtTIsBWn36hi_d4KTxPd2Zh1dsZMVnKK8k"
bing = ""
yandex = ""
pinterest = ""
baidu = "code-VsfDko5mls"
so = ""
sogou = "OTqUhL8vdL"

#  网站 SEO 配置
[seo]
# 图片 URL
image = ""
# 缩略图 URL
thumbnailUrl = ""

#  网站分析配置
[analytics]
enable = true
# Google Analytics
[analytics.google]
id = "G-Y7BJE11JP4"
# 是否匿名化用户 IP
anonymizeIP = true
# Fathom Analytics
[analytics.fathom]
id = ""
# 自行托管追踪器时的主机路径
server = ""

#  Cookie 许可配置
[cookieconsent]
enable = true
# 用于 Cookie 许可横幅的文本字符串
[cookieconsent.content]
message = ""
dismiss = ""
link = ""

#  第三方库文件的 CDN 设置
[cdn]
# CDN 数据文件名称，默认不启用
# ("jsdelivr.yml", "unpkg.yml")
# 位于 "themes/FixIt/assets/data/cdn/" 目录
# 可以在你的项目下相同路径存放你自己的数据文件：
# "assets/data/cdn/"
# data = "unpkg.yml"

#  兼容性设置
[compatibility]
# 是否使用 Polyfill.io 来兼容旧式浏览器
polyfill = false
# 是否使用 object-fit-images 来兼容旧式浏览器
objectFit = false

#  页面最后添加自定义 JS
# "_custom.js" 位于 "themes/FixIt/assets/js" 目录
# 可以在你的项目下相同路径存放你自己的自定义 JS 文件：
# "assets/js/_custom.js"
[customJS]
enable = true
#  在左上角或者右上角显示 GitHub 开源链接
[githubCorner]
enable = true
permalink = "https://github.com/dilless"
title = "在 GitHub 上找到我"
position = "right" # left, right
#  Gravatar 设置
[gravatar]
# Gravatar 主机，默认：“www.gravatar.com”
host = "www.gravatar.com" # "cn.gravatar.com", "gravatar.loli.net"
style = "" # "", mp, identicon, monsterid, wavatar, retro, blank, robohash
#  开发者选项
[dev]
enable = false
# 检查更新
c4u = false
# 请勿公开展示！
githubToken = ""
# 移动端开发者工具配置
[dev.mDevtools]
enable = false
# 支持 "vConsole", "eruda"
type = "vConsole"